version: "3.9"

x-common-variables: &common-variables
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_DB:-template}

services:
  dbpg: 
    container_name: postgres
    image: postgres
    environment:
      <<: *common-variables
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend 
    restart: unless-stopped

  web:
    environment:
      <<: *common-variables
      POSTGRES_HOST: dbpg
      MAX_CONCURRENCY: 8
      HOST: "0.0.0.0"
      PORT: "5000"
    image: kms:test
    build:
      context: . 
    ports:
      - "5000:5000"
    depends_on:
      - dbpg 
    volumes:
      - ./:/app
    networks:
      - backend 
    restart: unless-stopped


networks:
  backend:
    driver: bridge
